import os
import io
import time
import threading
from datetime import datetime, timezone

from flask import Flask, request, jsonify, render_template_string
from PIL import Image

app = Flask(__name__)

# ============================================================
# ALUCARD V2.1 — GOTHIC MARKET INTELLIGENCE
# Screen-feed compatible
# ============================================================

TOKEN = os.getenv("RYU_FEED_TOKEN", "").strip()

STATE_LOCK = threading.Lock()

state = {
    "asset": "UNKNOWN",
    "price": 0.0,
    "signal": "WAIT",
    "confidence": 0,
    "entry": 0.0,
    "entry_window": 12,
    "countdown": 0,
    "countdown_status": "WAITING",
    "candles": 0,
    "feed": "WAITING",
    "screen": "WAITING",
    "image_received": False,
    "timeframe": "1m",
    "payout": 0,
    "analysis": "Waiting for usable market data.",
    "last_update": 0,
    "last_frame": 0,
    "signal_started": 0,
    "signal_expires": 0,
}

# ============================================================
# POCKET OPTION ASSET MENU
# The list is intentionally broad. Pocket Option can change
# availability/payouts, so this dashboard does not fake payouts.
# ============================================================

ASSETS = {
    "Currency": [
        "EUR/USD",
        "GBP/USD",
        "USD/JPY",
        "USD/CHF",
        "USD/CAD",
        "AUD/USD",
        "NZD/USD",
        "EUR/GBP",
        "EUR/JPY",
        "GBP/JPY",
        "AUD/JPY",
        "AUD/CAD",
        "AUD/CHF",
        "AUD/NZD",
        "CAD/JPY",
        "CAD/CHF",
        "CHF/JPY",
        "EUR/CHF",
        "EUR/NZD",
        "GBP/AUD",
        "GBP/CHF",
        "NZD/JPY",
    ],

    "OTC Currency": [
        "EUR/USD OTC",
        "GBP/USD OTC",
        "USD/JPY OTC",
        "USD/CHF OTC",
        "USD/CAD OTC",
        "AUD/USD OTC",
        "NZD/USD OTC",
        "EUR/GBP OTC",
        "EUR/JPY OTC",
        "GBP/JPY OTC",
        "AUD/JPY OTC",
        "AUD/CAD OTC",
        "AUD/CHF OTC",
        "AUD/NZD OTC",
        "CAD/JPY OTC",
        "CAD/CHF OTC",
        "CHF/JPY OTC",
        "EUR/CHF OTC",
        "EUR/NZD OTC",
        "GBP/AUD OTC",
        "NZD/JPY OTC",
        "EUR/TRY OTC",
        "EUR/HUF OTC",
        "EUR/RUB OTC",
        "USD/RUB OTC",
        "USD/CNH OTC",
        "USD/INR OTC",
        "USD/IDR OTC",
        "USD/MYR OTC",
        "USD/SGD OTC",
        "USD/THB OTC",
        "USD/VND OTC",
        "USD/PKR OTC",
        "USD/PHP OTC",
        "USD/BDT OTC",
        "USD/EGP OTC",
        "USD/DZD OTC",
        "USD/CLP OTC",
        "USD/COP OTC",
        "USD/MXN OTC",
        "USD/BRL OTC",
        "USD/ARS OTC",
        "KES/USD OTC",
        "NGN/USD OTC",
        "ZAR/USD OTC",
        "YER/USD OTC",
        "TND/USD OTC",
        "MAD/USD OTC",
        "UAH/USD OTC",
        "LBP/USD OTC",
        "BHD/CNY OTC",
        "AED/CNY OTC",
        "SAR/CNY OTC",
        "QAR/CNY OTC",
        "OMR/CNY OTC",
        "JOD/CNY OTC",
    ],

    "Commodities": [
        "Gold",
        "Silver",
        "Brent Oil",
        "WTI Crude Oil",
        "Natural Gas",
        "Platinum spot",
        "Palladium spot",
    ],

    "OTC Commodities": [
        "Gold OTC",
        "Silver OTC",
        "Brent Oil OTC",
        "WTI Crude Oil OTC",
        "Natural Gas OTC",
        "Platinum spot OTC",
        "Palladium spot OTC",
    ],

    "Stocks": [
        "Apple",
        "Microsoft",
        "Amazon",
        "Tesla",
        "Intel",
        "Cisco",
        "Netflix",
        "Alibaba",
        "VISA",
        "American Express",
        "Boeing Company",
        "ExxonMobil",
        "McDonald's",
        "Johnson & Johnson",
        "Pfizer Inc",
        "FedEx",
        "Citigroup Inc",
        "GameStop Corp",
        "FACEBOOK INC",
        "Advanced Micro Devices",
        "Palantir Technologies",
        "Coinbase Global",
        "Marathon Digital Holdings",
    ],

    "OTC Stocks": [
        "Apple OTC",
        "Microsoft OTC",
        "Amazon OTC",
        "Tesla OTC",
        "Intel OTC",
        "Cisco OTC",
        "Netflix OTC",
        "Alibaba OTC",
        "VISA OTC",
        "American Express OTC",
        "Boeing Company OTC",
        "ExxonMobil OTC",
        "McDonald's OTC",
        "Johnson & Johnson OTC",
        "Pfizer Inc OTC",
        "FedEx OTC",
        "Citigroup Inc OTC",
        "GameStop Corp OTC",
        "FACEBOOK INC OTC",
        "Advanced Micro Devices OTC",
        "Palantir Technologies OTC",
        "Coinbase Global OTC",
        "Marathon Digital Holdings OTC",
        "VIX OTC",
    ],

    "Indices": [
        "US100",
        "SP500",
        "DJI30",
        "D30/EUR",
        "E35EUR",
        "E50EUR",
        "F40EUR",
        "100GBP",
        "JPN225",
        "AUS 200",
        "CAC 40",
        "HONG KONG 33",
    ],

    "OTC Indices": [
        "US100 OTC",
        "SP500 OTC",
        "DJI30 OTC",
        "D30EUR OTC",
        "E35EUR OTC",
        "E50EUR OTC",
        "F40EUR OTC",
        "100GBP OTC",
        "JPN225 OTC",
        "AUS 200 OTC",
    ],

    "Cryptocurrencies": [
        "Bitcoin",
        "Ethereum",
        "Litecoin",
        "Bitcoin ETF",
        "BCH/EUR",
        "BCH/GBP",
        "BCH/JPY",
        "BTC/GBP",
        "BTC/JPY",
        "Chainlink",
        "Dash",
        "BNB",
        "Solana",
        "Cardano",
        "TRON",
        "Toncoin",
        "Avalanche",
        "Dogecoin",
        "Polkadot",
        "Polygon",
    ],

    "OTC Crypto": [
        "Bitcoin OTC",
        "Ethereum OTC",
        "Litecoin OTC",
        "Bitcoin ETF OTC",
        "BNB OTC",
        "Sol
